ipfs_endpoint: /ip4/127.0.0.1/tcp/5001 #ipfs_endpoint must be in multiaddr format: https://github.com/multiformats/multiaddr#encoding
metadata_endpoint: https://api.appliedprimate.dev/sentinels/metadata
image_processor_mappings:
    gm_mappings:
        Trippy: ./ape/mugs/TRIPPY.png
        Crystal: ./ape/mugs/CRYSTAL.png
        Ice: ./ape/mugs/ICE.png
        Demon: ./ape/mugs/DEMON.png
        DMT: ./ape/mugs/DMT.png
        Fire: ./ape/mugs/FIRE.png
        Reef: ./ape/mugs/REEF.png
        Jelly: ./ape/mugs/JELLY.png
        Runes: ./ape/mugs/RUNES.png
        Golem: ./ape/mugs/GOLEM.png
        Radioactive: ./ape/mugs/RADIOACTIVE.png
        Electric: ./ape/mugs/ELECTRIC.png
        Robot: ./ape/mugs/ROBOT.png
        Death Bot: ./ape/mugs/DEATHBOT.png
        Gold: ./ape/mugs/GOLD.png
        Noise: ./ape/mugs/NOISE.png
        Zombie: ./ape/mugs/ZOMBIE.png
        Swamp: ./ape/mugs/SWAMP.png
        Holo R: ./ape/mugs/HOLOR.png
        Holo G: ./ape/mugs/HOLOG.png
        Holo B: ./ape/mugs/HOLOB.png
        Azul: ./ape/mugs/AZUL.png
