#ipfs_endpoint must be in multiaddr format: https://github.com/multiformats/multiaddr#encoding or fully qualified URL
ipfs_endpoint: https://gateway.ipfs.io
log_level: debug
metadata_endpoint: https://api.appliedprimate.dev/sentinels/metadata
discord_bot_token: APE_DISCORD_BOT_TOKEN #can set in env as APE_DISCORD_BOT_TOKEN
image_processor_mappings:
    gm_mappings:
        trippy: 
            lab: ./ape/gm_assets/TRIPPY.png
            path: ./ape/gm_assets/TRIPPY_PATH.png
        crystal: 
            lab: ./ape/gm_assets/CRYSTAL.png
            path: ./ape/gm_assets/CRYSTAL_PATH.png
        ice: 
            lab: ./ape/gm_assets/ICE.png
            path: ./ape/gm_assets/ICE_PATH.png
        demon:
            lab: ./ape/gm_assets/DEMON.png
            path: ./ape/gm_assets/DEMON_PATH.png
        dmt: 
            lab: ./ape/gm_assets/DMT.png
            path: ./ape/gm_assets/DMT_PATH.png
        fire: 
            lab: ./ape/gm_assets/FIRE.png
            path: ./ape/gm_assets/FIRE_PATH.png
        reef: 
            lab: ./ape/gm_assets/REEF.png
            path: ./ape/gm_assets/REEF_PATH.png
        jelly:
            lab: ./ape/gm_assets/JELLY.png
            path: ./ape/gm_assets/JELLY_PATH.png
        runes:
            lab: ./ape/gm_assets/RUNES.png
            path: ./ape/gm_assets/RUNES_PATH.png
        golem: 
            lab: ./ape/gm_assets/GOLEM.png
            path: ./ape/gm_assets/GOLEM_PATH.png
        radioactive:
            lab: ./ape/gm_assets/RADIOACTIVE.png
            path: ./ape/gm_assets/RADIOACTIVE_PATH.png
        electric: 
            lab: ./ape/gm_assets/ELECTRIC.png
            path: ./ape/gm_assets/ELECTRIC_PATH.png
        robot: 
            lab: ./ape/gm_assets/ROBOT.png
            path: ./ape/gm_assets/ROBOT_PATH.png
        death bot: 
            lab: ./ape/gm_assets/DEATHBOT.png
            path: ./ape/gm_assets/DEATHBOT_PATH.png
        gold: 
            lab: ./ape/gm_assets/GOLD.png
        noise: 
            lab: ./ape/gm_assets/NOISE.png
            path: ./ape/gm_assets/NOISE_PATH.png
        zombie: 
            lab: ./ape/gm_assets/ZOMBIE.png
            path: ./ape/gm_assets/ZOMBIE_PATH.png
        swamp: 
            lab: ./ape/gm_assets/SWAMP.png
            path: ./ape/gm_assets/SWAMP_PATH.png
        holo r: 
            lab: ./ape/gm_assets/HOLOR.png
        holo g: 
            lab: ./ape/gm_assets/HOLOG.png
        holo b: 
            lab: ./ape/gm_assets/HOLOB.png
        azul:
            lab: ./ape/gm_assets/AZUL.png
    base_gm_smoke: ./ape/gm_assets/BASE_GM_SMOKE.png
    base_gm_smoke_path: ./ape/gm_assets/BASE_GM_SMOKE_PATH.png
    base_gm_smoke_border: ./ape/gm_assets/BASE_GM_SMOKE_BORDER.png
    azul_gm_smoke: ./ape/gm_assets/AZUL_GM_SMOKE.png
    azul_gm_smoke_border: ./ape/gm_assets/AZUL_GM_SMOKE_BORDER.png


    filters:
        opacity: #for gm_smoke_border. Valid values are 0-1
            trippy: 
               name: trippy
               Default: 0.8
               Weights:
                   lab coat: 1
            crystal: 
               name: crystal
               Default: 0.8
            ice:
                name: ice
                Default: 0.8
            demon: 
               name: demon
               Default: 0.8
            dmt: 
               name: dmt
               Default: 0.8
               Weights:
                   lab coat: .75
            fire: 
               name: fire
               Default: 0.8
            reef: 
               name: reef
               Default: 0.8
            jelly: 
               name: jelly
               Default: 0.8
            runes: 
               name: runes
               Default: 0.8
            golem: 
               name: golem
               Default: 0.8
            radioactive: 
               name: radioactive
               Default: 0.8
            electric: 
               name: electric
               Default: 0.8
            robot: 
               name: robot
               Default: 0.8
            death bot: 
               name: death bot
               Default: 0.8
            gold: 
               name: gold
               Default: 0.85
            noise: 
               name: noise
               Default: 0.8
            zombie: 
               name: zombie
               Default: 0.8
            swamp: 
               name: swamp
               Default: 0.8
            holo r: 
               name: holo r
               Default: 0.8
            holo g: 
               name: holo g
               Default: 0.8
            holo b: 
               name: holo b
               Default: 0.8
            azul: 
               name: azul
               Default: 0.8
